# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Base' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift', '~> 4.3.1'                       #响应式函数框架
  pod 'RxCocoa', '~> 4.3.1'                       #响应式函数框架
  pod 'SnapKit', '~> 4.0.0'                       #布局框架
  pod 'Kingfisher', '~> 4.6.1'                    #图片框架
  

  
  # Pods for Base
  
end
